name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x", "17.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint:fix

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Cache Coverage
        id: cache-coverage
        uses: actions/cache@v3
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage

      - name: Upload coverage to Coveralls
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          verbose: true

      - name: Build
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    needs: [build]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint:fix

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Upload coverage to Coveralls
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          verbose: true

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
